[#header]
= Migrations

ifndef::env-github[]
:icons: font
endif::[]
ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:toc:
:toc-placement!:
:toclevels: 4

[#version-0-7-0]
== 0.6.0 -> 0.7.0

Before the 0.7.0 version in case any of the input files during the `generate-and-aggregate-documents` Maven goal or `generateAndAggregateDocuments` Gradle task was missing the documentation was created but the missing elements were not rendered into the document, because there was nothing to be read.

With the release of the 0.7.0 this changes and the build will fail, but it can be parametrized for both available goals/tasks.

Maven goals:

* generate-property-document
* generate-and-aggregate-documents

Gradle tasks:

* generatePropertyDocument
* generateAndAggregateDocuments

=== Maven

.pom.xml
[source,xml]
----
<executions>
    <execution>
        <id>generate-adoc</id>
        <phase>process-classes</phase>
        <goals>
            <goal>generate-property-document</goal>
        </goals>
        <configuration>
            <type>TYPE</type>
            <!--Set to true if the build should fail if the input file is missing, set to false if it should generate an empty document-->
            <failOnMissingInput>true</failOnMissingInput>
        </configuration>
    </execution>
    <execution>
        <id>generate-adoc</id>
        <phase>process-classes</phase>
        <goals>
            <goal>generate-and-aggregate-documents</goal>
        </goals>
        <configuration>
            <type>TYPE</type>
            <!--Set to true if the build should fail if the input file is missing, set to false if it should generate an empty document-->
            <failOnMissingInput>true</failOnMissingInput>
        </configuration>
    </execution>
</executions>
----

=== Gradle

[#version-0-6-1]
== 0.6.0 -> 0.6.1

No changes required.

[#version-0-6-0]
== 0.5.1 -> 0.6.0

=== Including environment format

Header appearance in the tables are now customizable, and to make sure the environment variable is also following the same configuration way the older configuration in the Maven and Gradle plugins are not going to work.

A new level of configuration is introduced, it can be configured with the `contentCustomization` key in Maven and in Gradle.

==== Maven

.Till 0.5.1
[source,xml]
----
<execution>
    <id>generate-adoc</id>
    <phase>process-classes</phase>
    <goals>
        <goal>generate-property-document</goal>
    </goals>
    <configuration>
        <type>TYPE</type>
        <asciiDocCustomization>
            <markdownCustomization>
                <includeEnvFormat>true</includeEnvFormat>
            </markdownCustomization>
            <htmlCustomization>
                <includeEnvFormat>true</includeEnvFormat>
            </htmlCustomization>
            <xmlCustomization>
                <includeEnvFormat>true</includeEnvFormat>
            </xmlCustomization>
            <asciiDocCustomization>
                <includeEnvFormat>true</includeEnvFormat>
            </asciiDocCustomization>
        </asciiDocCustomization>
    </configuration>
</execution>

----

.From 0.6.0
[source,xml]
----
<execution>
    <id>generate-adoc</id>
    <phase>process-classes</phase>
    <goals>
        <goal>generate-property-document</goal>
    </goals>
    <configuration>
        <type>TYPE</type>
        <asciiDocCustomization>
            <markdownCustomization>
                <contentCustomization>
                    <includeEnvFormat>true</includeEnvFormat>
                </contentCustomization>
            </markdownCustomization>
            <htmlCustomization>
                <contentCustomization>
                    <includeEnvFormat>true</includeEnvFormat>
                </contentCustomization>
            </htmlCustomization>
            <xmlCustomization>
                <contentCustomization>
                    <includeEnvFormat>true</includeEnvFormat>
                </contentCustomization>
            </xmlCustomization>
            <asciiDocCustomization>
                <contentCustomization>
                    <includeEnvFormat>true</includeEnvFormat>
                </contentCustomization>
            </asciiDocCustomization>
        </asciiDocCustomization>
    </configuration>
</execution>
----

==== Gradle

.Till 0.5.1
[source,groovy]
----
tasks.register('generateAdoc') {
    dependsOn generatePropertyDocument {
        documentName = "Hello World"
        type = "ADOC"
        asciiDocCustomization {
            includeEnvFormat = true
        }
    }
}

tasks.register('generateMarkdown') {
    dependsOn generatePropertyDocument {
        documentName = "Hello World"
        type = "MARKDOWN"
        markdownCustomization {
            includeEnvFormat = true
        }
    }
}

tasks.register('generateHtml') {
    dependsOn generatePropertyDocument {
        documentName = "Hello World"
        type = "HTML"
        htmlCustomization {
            includeEnvFormat = true
        }
    }
}

tasks.register('generateXml') {
    dependsOn generatePropertyDocument {
        documentName = "Hello World"
        type = "XML"
        xmlCustomization {
            includeEnvFormat = true
        }
    }
}
----

.From 0.6.0
[source,groovy]
----
tasks.register('generateAdoc') {
    dependsOn generatePropertyDocument {
        documentName = "Hello World"
        type = "ADOC"
        asciiDocCustomization {
            contentCustomization {
                includeEnvFormat = true
            }
        }
    }
}

tasks.register('generateMarkdown') {
    dependsOn generatePropertyDocument {
        documentName = "Hello World"
        type = "MARKDOWN"
        markdownCustomization {
            contentCustomization {
                includeEnvFormat = true
            }
        }
    }
}

tasks.register('generateHtml') {
    dependsOn generatePropertyDocument {
        documentName = "Hello World"
        type = "HTML"
        htmlCustomization {
            contentCustomization {
                includeEnvFormat = true
            }
        }
    }
}

tasks.register('generateXml') {
    dependsOn generatePropertyDocument {
        documentName = "Hello World"
        type = "XML"
        xmlCustomization {
            contentCustomization {
                includeEnvFormat = true
            }
        }
    }
}
----

[#version-0-5-1]
== 0.5.0 -> 0.5.1

No changes required.

[#version-0-5-0]
== 0.4.0 -> 0.5.0

No changes required.

[#version-0-4-0]
== 0.3.0 -> 0.4.0

No changes required.

[#version-0-3-0]
== 0.2.4 -> 0.3.0

No changes required.

[#version-0-2-4]
== 0.2.3 -> 0.2.4

No changes required.

[#version-0-2-3]
== 0.2.2 -> 0.2.3

No changes required.

[#version-0-2-2]
== 0.2.1 -> 0.2.2

No changes required.

[#version-0-2-1]
== 0.2.0 -> 0.2.1

No changes required.

[#version-0-2-0]
== 0.1.1 -> 0.2.0

No changes required.

[#version-0-1-1]
== 0.1.0 -> 0.1.1

No changes required.
