[#header]
= Spring Configuration Property Documenter - Template Customization
ifndef::env-github[]
:icons: font
endif::[]
ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:toc:
:toc-placement!:
:toclevels: 4

As written in the *README* file the core module is using https://jknack.github.io/handlebars.java/[Handlebars] as the templating engine. With that we are able to create smaller files and we can render them together.

If you would like to use your own templates as inputs you should first read through the following section to know which parameters you can use in your template.

toc::[]

== Default templates

The provided/packaged templates can be found here:

* *spring-configuration-property-documenter-core/src/main/resources/templates/single*
** Contains the basic templates for a single module
* *spring-configuration-property-documenter-core/src/main/resources/templates/aggregated*
** Contains templates that could be used for multiple document aggregation
* *spring-configuration-property-documenter-core/src/main/resources/templates/partials*
** Contains the templates for the content, and for the HTML a few helper templates

=== AsciiDoc customizations

The final AsciiDoc files when they are being included, the rendered files are utilizing the following AsciiDoc related features:

* https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/#tag-filtering[Tag filtering]
*  https://docs.asciidoctor.org/asciidoc/latest/directives/ifdef-ifndef/[ifdef and ifndef Directives]

==== Tag filtering

Every configuration property key is wrapped in a tag, and on include any tag can be ignored, or a specific list of configuration property keys can be set to include in the main documentation

.Example
[source,adoc]
----
// tag::this.is.module.a[]
=== this.is.module.a
*Class:* `com.example.multimodulea.ModuleAProperty`

[cols="2,1,3,1,1"]
|===
|Key |Type |Description |Default value |Deprecation

|variable-a
|java.lang.String
|This is my variable from module A.
|Default value for module A
|


|===
// end::this.is.module.a[]
----

.Example include
[source,adoc]
----
\include::file.adoc[tags=my.property.key.a;my.property.key.b]
\include::file.adoc[tags=!my.property.key.a;my.property.key.b]
----

===== ifdef and ifndef Directives
With the `ifdef` and `ifndef` directives the content of the document can be manipulated and the tool gives you the following directives to play with:

* `property-group-simple-title` - Define this attribute to have the included document's header style just a simple text and not a header
** It can be good if the configuration documentation is being included in a collapsible section
* `property-group-discrete-heading` - Define this attribute if the included document's headers should be rendered as https://docs.asciidoctor.org/asciidoc/latest/blocks/discrete-headings/[discrete headings]
** It can be good if the configuration documentation is being included in a collapsible section
* If none of the attributes are configured, the typical (= based) headings will be used.

.Example file
[source,adoc]
----
ifndef::property-group-simple-title,property-group-discrete-heading[=== this.is.module.a +]
ifdef::property-group-simple-title[.*_this.is.module.a_* +]
ifdef::property-group-discrete-heading[]
[discrete]
=== this.is.module.a
endif::[]
*Class:* `com.example.multimodulea.ModuleAProperty`

[cols="2,1,3,1,1"]
|===
|Key |Type |Description |Default value |Deprecation

|variable-a
|java.lang.String
|This is my variable from module A.
|Default value for module A
|


|===
----

.Example include
[source,adoc]
----
:property-group-simple-title: //<.>
include::file.adoc[]
:property-group-simple-title!: //<.>


:property-group-discrete-heading: //<.>
include::file.adoc[]
:property-group-discrete-heading!://<.>
----
<1> Enable the simple titles
<2> Disabled the simple titles to make sure another included files are not inheriting the attributes
<3> Enable the discrete headings
<4> Disabled the discrete headings to make sure another included files are not inheriting the attributes

== Custom templates

You are not forced to use our templates, we can understand it is not your taste and maybe the customization options for the provided ones are not that flexible for your (for example the HTML format).

By default, as written above https://jknack.github.io/handlebars.java/[Handlebars] is being used as the primary templating engine, and we are using the default settings, so if you create a template for yourself make sure you know the basic syntax and for all the templates the `.hbs` extension should be used, please check the provided templates for more information.

NOTE: For a single document only one template is being used, but for the aggregated documents the tool is using multiple templates to render the final template, it is because we are compiling the header, footer and the content section after each other, and we are merging them in the end.

The custom templates can be provided with the Maven and Gradle plugins as well or with <<usage-jbang#header, JBang>> if this is your preference.

NOTE: Make sure you use your custom template file names with the `.hbs` extension, because Handlebars will put it to the end of the file.

== Custom template compiler

By default, as written above https://jknack.github.io/handlebars.java/[Handlebars] is being used as the primary templating engine, but it is fully understood if this tool does not suit your requirements, there are a lot of out there, and you might want to use that as the templating engine.

*It is doable!*

The tool is coming with an SPI (Service Provider Interface) extension where you can use your own `org.rodnansol.core.generator.template.TemplateCompiler` implementation and from the Maven or Gradle plugin you can set the compiler's name.

TIP: It has been available since the *0.2.0* version.

You only have to implement one method for now:

[source,java]
----
public interface TemplateCompiler {

    /**
     * Compiles the template with the given template data.
     * <p>
     * If the template is not found an exception  must be raised.
     *
     * @param templatePath path to the template that the compiler can understand and work with.
     * @param templateData template data.
     * @return templated populated and compiled with the given template data.
     * @throws DocumentGenerationException when the template compiler occurs an error.
     */
    String compileTemplate(String templatePath, TemplateData templateData) throws DocumentGenerationException;
}
----

* `templatePath` variable is that what you can set for yourself from the Maven and Gradle plugin which should be the path to the template that must be compiled.
* `templateData` variable is an object that is holding the converted data from the `spring-configuration-metadata.json` file. Check below for the available fields

=== Register custom template compiler

To register your service create a file named `org.rodnansol.core.generator.template.TemplateCompiler` under the `META-INF/services` directory and put your class's fully qualified name into the file.

To make sure you have the necessary classes, at least for now, you have to add the following dependency to your project:

.pom.xml
[source,xml]
----
<dependency>
    <groupId>org.rodnansol</groupId>
    <artifactId>spring-configuration-property-documenter-core</artifactId>
    <version>${project.version}</version>
</dependency>
----

TIP: If this feature is going to get more visibility we will create an API module that would contain only the necessary classes to make sure your project is not polluted with a plugin dependency.

[WARNING]
The template variables are going to be the same, but if there is any compatibility issue with your compiling engine please let us know about the problem and open an issue to make sure we can handle these problems as well.

.Registration example
[%collapsible%]
====
.pom.xml
[source,xml]
----
<plugin>
                <groupId>org.rodnansol</groupId>
                <artifactId>spring-configuration-property-documenter-maven-plugin</artifactId>
                <version>999-SNAPSHOT</version>
                <dependencies>
                    <dependency>
                        <groupId>org.rodnansol.example</groupId>
                        <artifactId>custom-template-compiler</artifactId>
                        <version>${project.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>generate-markdown-custom-template-compiler</id>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>generate-property-document</goal>
                        </goals>
                        <configuration>
                            <type>MARKDOWN</type>
                            <templateCompilerName>com.example.custom.CustomTemplateCompiler</templateCompilerName>
                            <outputFile>target/custom-compiler-document.md</outputFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
----

NOTE: Make sure you add the Maven module that contains the service registration (with the META-INF/services folder) to the plugin's dependency list, unless it will not recognize it.

====

TIP: For a working example please check the *samples/multi-module* directory's *multi-module-c* and *custom-template-compiler* module.

== Template variables

There are few Java classes to be discovered if you wish:

- `org.rodnansol.core.generator.MainTemplateData`
- `org.rodnansol.core.generator.SubTemplateData`
- `org.rodnansol.core.generator.PropertyGroup`
- `org.rodnansol.core.generator.Property`
- `org.rodnansol.core.generator.PropertyDeprecation`

.Template variables (MainTemplateData)
|===
|Variable |Type |Description |Since

|mainName
|String
|Main header name, this can be configured, most times it is the name of the project or module
|0.1.0

|propertyGroups
|List<PropertyGroup>
|List of the property groups that has been read and converted from the `spring-configuration-metadata.json`
|0.1.0

|subTemplateDataList
|List<SubTemplateData>
|If multiple file aggregation is happening than this is going to contain all the incoming module data.
|0.1.0

|mainDescription
|String
|Main description that is customizable
|0.1.0

|generationDate
|LocalDateTime
|The date time of the template generation
|0.1.0

|templateCustomization
|TemplateCustomization
|An object that can be used to customize a given template (see <<template-customizations,here>>)
|0.2.0

|===

.Template variables (SubTemplateData)
|===
|Variable |Type |Description |Since

|moduleName
|String
|Name of the module, in case of aggregation it can be a module name
|0.1.0

|propertyGroups
|List<PropertyGroup>
|List of the property groups that has been read and converted from the `spring-configuration-metadata.json`
|0.1.0

|moduleDescription
|String
|Module description that is customizable
|0.1.0

|generationDate
|LocalDateTime
|The date time of the template generation
|0.1.0

|===

.Template variables (PropertyGroup)
|===
|Variable |Type |Description |Since

|groupName
|String
|Name of the group, this is basically the prefix you set in the `@ConfigurationProperties` annotation
|0.1.0

|type
|String
|The name of the class, if it is a nested class it will be the name of that class
|0.1.0


|sourceType
|String
|The name of the class, if it is a nested class it will be the name of that parent class
|0.1.0

|properties
|List<Property>
|List of the properties
|0.1.0

|parentGroup
|PropertyGroup
|Parent property group
|0.1.0

|childrenGroups
|List<PropertyGroup>
|Children property groups, in case of parent and nester class associations
|0.1.0

|===

.Template variables (Property)
|===
|Variable |Type |Description |Since

|fqName
|String
|Fully qualified name
|0.1.0

|type
|String
|The Java type
|0.1.0

|key
|String
|Property key
|0.1.0

|description
|String
|Description of the property, read from the JavaDoc
|0.1.0

|defaultValue
|String
|Default value if specified
|0.1.0

|propertyDeprecation
|PropertyDeprecation
|If the property is marked as deprecated data about that
|0.1.0

|===

.Template variables (PropertyDeprecation)
|===
|Variable |Type |Description |Since

|reason
|String
|Reason of the deprecation
|0.1.0

|replacement
|String
|The replacement of the specific key
|0.1.0

|===

[#template-customizations]
=== TemplateCustomization subclasses

.`org.rodnansol.core.generator.template.customization.AbstractTemplateCustomization`
[cols="1,1,4,1,1"]
|===
|Variable |Type |Description |Default value |Since

|headerEnabled
|boolean
|Controls if the header section (main module name and main module description) should be enabled/visible or not
|*true*
|0.2.0

|tableOfContentsEnabled
|boolean
|Controls if the "Table of contents" sections should be enabled or not
|*true*
|0.2.0

|includeUnknownGroup
|boolean
|Controls if the properties without any known group should be included or not. It can happen if the input metadata JSON file is missing the group association with its properties.
|*true*
|0.3.0

|includeGenerationDate
|boolean
|Controls if the generation date should be rendered to the final document or not.
|*true*
|0.4.0

|includeEnvFormat
|boolean
|Controls if the environment variable form of the properties should be rendered into the final document or not.
|*false*
|0.4.0

|===

.`org.rodnansol.core.generator.template.customization.MarkdownTemplateCustomization`
[cols="1,1,4,1,1"]
|===
|Variable |Type |Description |Default value |Since


|===

.`org.rodnansol.core.generator.template.customization.XmlTemplateCustomization`
[cols="1,1,4,1,1"]
|===
|Variable |Type |Description |Default value |Since


|===

.`org.rodnansol.core.generator.template.customization.AsciiDocTemplateCustomization`
[cols="1,1,4,2,1"]
|===
|Variable |Type |Description |Default value |Since

|tocTitle
|String
|"Table of Contents" replacement title
|Table of Contents
|0.2.0

|tocPlacement
|TocPlacement (AUTO, LEFT, RIGHT)
|"Table of Contents" placement
|AUTO
|0.2.0

|tocLevels
|int
|"Table of Contents" level/depth
|4
|0.2.0

|===

.`org.rodnansol.core.generator.template.customization.HtmlTemplateCustomization`
[cols="1,1,4,2,1"]
|===
|Variable |Type |Description |Default value |Since

|backgroundColor
|String
|Table and associated elements background color
|#7db04b
|0.2.0

|linkColor
|String
|Link (<a>) text color
|black
|0.2.0

|collapsibleHoverColor
|String
|Table of content based collapsible block hover color
|#96d95c
|0.2.0

|codeColor
|String
|<code> section color
|#eeeeee
|0.2.0

|evenTableRowColor
|String
|Even table row's color
|#f3f3f3
|0.2.0

|lastTableRowColor
|String
|Last table row's color
|#009879
|0.2.0

|tableRowColor
|String
|Table row color
|#ffffff
|0.2.0

|tableRowBorderColor
|String
|Border color of the table rows
|#dddddd
|0.2.0

|textColor
|String
|Text color
|white
|0.2.0

|===

NOTE: The full stylesheet can be found here in this file: https://github.com/rodnansol/spring-configuration-property-documenter/blob/master/spring-configuration-property-documenter-core/src/main/resources/templates/partials/html/header.html.hbs
